#!/bin/sh
HISTFILE="$HOME"/.local/share/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
eval "$(fnm env)"
#eval "$(zoxide init zsh)"
